"""Celery ID and VLANs columns

Revision ID: 1716f4c828db
Revises: 9ad1c5c3f7af
Create Date: 2022-08-30 14:06:08.667792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1716f4c828db'
down_revision = '9ad1c5c3f7af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('celery_id', sa.String(), nullable=True))
    op.add_column('entries', sa.Column('vlan_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entries', sa.Column('modified_vlan_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'modified_vlan_settings')
    op.drop_column('entries', 'vlan_settings')
    op.drop_column('entries', 'celery_id')
    # ### end Alembic commands ###
