"""Firmware column in Model model

Revision ID: 7e3019b69df5
Revises: 1716f4c828db
Create Date: 2022-08-30 15:04:37.197677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3019b69df5'
down_revision = '1716f4c828db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('firmware', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'firmware')
    # ### end Alembic commands ###
